### ISSUE TITLE
When are the latest changes going to be published as a version?

### ISSUE THREAD

**Issue by danyfel80** [cytomine/Cytomine-java-client#10]
Hello there, I'm wondering when are the latest changes going to be packed as new release version. I currently use my local version with the changes from ULiege branch but I would like to have the version directly from github as it happens with version 1.1.2

Best regards,
Daniel

**Comment by geektortoise** [comment]
Hello, 

Sorry, we are two years later but this answer could be useful for other users.

Globally, the ULiège team has its own development roadmap, our will is to integrate the features (all relevant) they develop. However, this integration takes time and I'm unable to give a global time estimation between the release of a ULiège feature and its integration into this repository.

Specifically to this client, I released the v2.0.0 with the OOP paradigm that I started years ago and a future release with the specific feature to the Softwares will be released the next month.
