### ISSUE TITLE
Java exception occurred: java.lang.VerifyError: org/apache/http/params/SyncBasicHttpParams

### ISSUE THREAD

**Issue by aled88** [cytomine/Cytomine-java-client#11]
Hi 
i am running the jar package using Matlab 2016a .
**version -java**
Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

I did a search and found out that the verify error is due to compiler . Say I need to do something like using the same compiler or compile it from scratch. How can i solve this correctly?

**Matlab code:**
CYTOMINE_URL = 'http://';
PUBLIC_KEY = 'xx';
PRIVATE_KEY = 'xx';
javaaddpath('E:\urlread2\cytomine-java-client.jar');
javaclasspath

import be.cytomine.*
import be.cytomine.client.*
import be.cytomine.client.models.*
import be.cytomine.client.collections.*
cyto = Cytomine(CYTOMINE_URL, PUBLIC_KEY, PRIVATE_KEY);

**%%running this command generate error below**
cyto.getCurrentUser().get('username')

```
Java exception occurred:
java.lang.VerifyError: org/apache/http/params/SyncBasicHttpParams

	at
    org.apache.http.impl.client.DefaultHttpClient.createHttpParams(DefaultHttpClient.java:157)
    
	at org.apache.http.impl.client.AbstractHttpClient.getParams(AbstractHttpClient.java:447)

	at
    org.apache.http.impl.client.AbstractHttpClient.createClientConnectionManager(AbstractHttpClient.java:308)
    
	at
    org.apache.http.impl.client.AbstractHttpClient.getConnectionManager(AbstractHttpClient.java:465)
    
	at
    org.apache.http.impl.client.AbstractHttpClient.createHttpContext(AbstractHttpClient.java:285)
    
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:799)

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)

	at be.cytomine.client.HttpClient.get(HttpClient.java:144)

	at be.cytomine.client.Cytomine.fetchModel(Cytomine.java:247)

	at be.cytomine.client.Cytomine.getCurrentUser(Cytomine.java:871)
```

**Comment by aled88** [comment]
apparently it conflicted with matlab existing httpcore  and common package. commenting it out in path remove the errors. but still getting no result in 
`cyto.getCurrentUser().get('username')`

not sure how to get it properly set up.

**Comment by geektortoise** [comment]
Hello,

The client jar is compiled with java8. 
So, if you want to use it with a java7 version, you need to compile it yourself from the sources.
(Or upgrade your java version)

**Comment by aled88** [comment]
Thank you. Actually after some reading, I managed to single file compile on the HttpClient.java with it dependencies and can get it run on java 1.7. I will upgrade the java version to run all the features then.

**Comment by aled88** [comment]
Finally got it to work, but with some error

log4j:WARN No appenders could be found for logger (be.cytomine.client.HttpClient).
log4j:WARN Please initialize the log4j system properly.

**Comment by aled88** [comment]
Right now i am trying to implement the HttpClient.java in matlab but it fail to connect. 

%% Matlab try 
clc;clear;
cy_public = 'bedaf676-bab0-4e25-a0dc-xxxxxxx';
cy_private = '30a236a4-ab5c-4514-86fa-xxxxxxx';
url = 'http://url/api/annotation/5357434.json';

formatOut = 'ddd, dd mmm yyyy HH:MM:SS';
tt = datetime('now','TimeZone','UTC');
cy_date2 = [datestr(tt,formatOut),' +0000'];
cy_date = [cy_date2,char(10)];
cy_url = '/api/annotation/5357434.json';
cy_action = ['GET',char(10),char(10),char(10)];
cy_sha1 = doHMAC_SHA1([cy_action,cy_date,cy_url],cy_private);
payload_uint8=uint8(cy_sha1);
payload=char(org.apache.commons.codec.binary.Base64.encodeBase64(payload_uint8))';
cy_sign=['CYTOMINE ',cy_public,':',payload];

headers = javaArray('java.lang.String',3);
date_ = java.lang.String('date');
accept_ = java.lang.String('accept');
authorization_ = java.lang.String('authorization');
value_1 = java.lang.String(cy_date2);
value_2 = java.lang.String('application/json,*/*');
value_3 = java.lang.String(cy_sign);
head1 = org.apache.http.message.BasicHeader(accept_,value_1);
head2 = org.apache.http.message.BasicHeader(date_,value_2);
head3 = org.apache.http.message.BasicHeader(authorization_,value_3);
headers = [head1 head2 head3];

%%handler = sun.net.www.protocol.http.Handler;
%%URL = java.net.URL([],url,handler);
URL = java.net.URL(url);
targetHost = org.apache.http.HttpHost(URL.getHost());
client = org.apache.http.impl.client.HttpClientBuilder.create().build();
localcontext = org.apache.http.client.protocol.HttpClientContext.create();

httpGet = org.apache.http.client.methods.HttpGet(URL.toString());
httpGet.setHeaders(headers); %%array headers
response = client.execute(targetHost, httpGet, localcontext);

response.getStatusLine().getStatusCode()
entityResponse = response.getEntity();
org.apache.commons.io.IOUtils.toString(entityResponse.getContent())

**Comment by aled88** [comment]
I have created another script with matlab 2017b  that can connect and fetch an annotation id. The confusing thing is sometimes it get the result at one try but most of the time it give 401 unauthorized error.

```
clc;clear all;

cy_public = 'bedaf676-bab0-4e25-a0dc-xxx';
cy_private = '30a236a4-ab5c-4514-86fa-xx';
url = 'http://local/api/annotation/5357434.json';

%%

formatOut = 'ddd, dd mmm yyyy HH:MM:SS';
tt = datetime('now','TimeZone','UTC');
cy_date = [datestr(tt,formatOut),' +0000'];
cy_url = [newline,'/api/annotation/5357434.json'];
cy_action = ['GET',newline,newline,newline];
hmac = System.Security.Cryptography.HMACSHA1(uint8(cy_private)).ComputeHash(uint8([cy_action,cy_date,cy_url]));
cy_sha1 = native2unicode(hmac);
%%%cy_sha1 = doHMAC_SHA1([cy_action,cy_date,cy_url],cy_private);
payload = base64encode(cy_sha1);
cy_sign=['CYTOMINE ',cy_public,':',payload];

    cy_header_1 = matlab.net.http.field.GenericField('date',cy_date);
    cy_header_2 = matlab.net.http.field.GenericField('X-Requested-With','XMLHttpRequest');
    cy_header_3 = matlab.net.http.field.GenericField('authorization',cy_sign); 
    cy_header_4 = matlab.net.http.field.GenericField('accept','application/json,*/*');
    cy_header_5 = matlab.net.http.field.GenericField('Accept-Encoding','identity');
    header = [cy_header_5 cy_header_1  cy_header_2 cy_header_3 cy_header_4];

    reqline = matlab.net.http.RequestLine('GET',cy_url,'HTTP/1.1');
    cy_req = matlab.net.http.RequestMessage(reqline,header,[]); 
    uri = matlab.net.URI(url);

    options = matlab.net.http.HTTPOptions('Authenticate',false);
   [completedrequest2,target] = complete(cy_req,uri,options)
   [response,completedrequest3,history] = send(completedrequest2,target,options)
    response.Body.Data
```

**Comment by aled88** [comment]
Hi,

I have finally successful on porting the connection with Matlab. I am planning to add more functionality with matlab. How can i contribute the script to this github section?

**Comment by geektortoise** [comment]
Hello, 

The best way to contribute is 
- to fork this repo if you want to extend/modify the java client. 
- to create a new repository if you want to create a new project (as a MathLab client)

Then we will discuss how to integrate it in the cytomine official projects.
